answer/urls.py
from django.conf.urls import include
from django.urls import path
from .views import IndexView, QuestionCreateView, QuestionDetailView, QuestionEditView, delete_question, delete_reply, ReplyEditView

app_name = 'answer'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('create/', QuestionCreateView.as_view(), name='create'),
    path('<int:pk>/', QuestionDetailView, name='detail'),
    path('<int:pk>/edit/', QuestionEditView.as_view(), name='edit'),
    path('<int:pk>/delete/', delete_question, name='delete'),
    path('<int:question_id>/reply/<int:pk>/delete',
         delete_reply, name='delete-reply'),
    path('<int:question_id>/reply/<int:pk>/edit/',
         ReplyEditView, name='edit-reply'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
from django.urls import path
from django.contrib import admin
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('answer/', include('answer.urls'), name='answer'),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('auth/', include('social_django.urls', namespace='social')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

answer/models.py
from django.db import models
from django.utils import timezone
from mdeditor.fields import MDTextField

from accounts.models import User


class Classiffication(models.Model):
    """"""
    name = models.CharField(verbose_name='分類名', max_length=255, unique=True,)
    order = models.IntegerField(verbose_name='並び順', unique=True)
    created_at = models.DateField(verbose_name='作成日', default=timezone.now)
    updated_at = models.DateField(verbose_name="更新日", auto_now=True)

    class Meta:
        ordering = ['order', ]
        verbose_name = '大分類'
        verbose_name_plural = '大分類'

    def __str__(self):
        return self.name


class Method(models.Model):
    """"""
    name = models.CharField(verbose_name='工法名', max_length=255, unique=True,)
    order = models.IntegerField(verbose_name='並び順', unique=True)
    created_at = models.DateField(verbose_name='作成日', default=timezone.now)
    updated_at = models.DateField(verbose_name="更新日", auto_now=True)

    class Meta:
        ordering = ['order', ]

    def __str__(self):
        return self.name


class Question(models.Model):
    """"""
    classiffication = models.ForeignKey(
        Classiffication, on_delete=models.CASCADE)
    method = models.ForeignKey(Method, on_delete=models.CASCADE)
    content = MDTextField(verbose_name='質問内容')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(verbose_name="作成日", default=timezone.now)
    updated_at = models.DateTimeField(verbose_name="更新日", auto_now=True)
    resolve = models.BooleanField(default=False)

    class Meta:
        ordering = ['-updated_at']

    def __str__(self):
        return self.content


class Reply(models.Model):
    """"""
    question = models.ForeignKey(
        Question, related_name='replies', on_delete=models.CASCADE)
    content = MDTextField(verbose_name='回答内容')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(verbose_name="作成日", default=timezone.now)
    updated_at = models.DateTimeField(verbose_name="更新日", auto_now=True)
    is_best_answer = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_at']

    def __str__(self):
        return self.content

answer/forms.py
from django.db.models import fields
from django.forms import ModelForm
from .models import Question, Reply


class QuestionForm(ModelForm):
    class Meta:
        model = Question
        fields = ('classiffication', 'method', 'content')
        labels = {
            'classiffication': '大分類',
            'method': '工法分類',
            'content': '質問内容',
        }


class ReplyForm(ModelForm):
    class Meta:
        model = Reply
        fields = ('content',)

answer/views.py
from django.core.checks import messages
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from .models import Classiffication, Question, Reply, Method
from .forms import QuestionForm, ReplyForm


class IndexView(LoginRequiredMixin, generic.ListView):
    model = Question
    template_name = 'answer/index.html'
    paginate_by = 3

    def get_queryset(self):
        request = self.request.GET
        s_content = request.get('content')
        s_class = request.get('classiffication')
        s_method = request.get('method')
        s_resolve = request.get('resolve')
        q_content = Q()
        q_class = Q()
        q_method = Q()
        q_resolve = Q()
        if s_content:
            q_content = Q(content__contains=s_content)
        if s_class:
            q_class = Q(classiffication=s_class)
        if s_method:
            q_method = Q(method=s_method)
        if s_resolve:
            q_resolve = Q(resolve=s_resolve)
        object_list = Question.objects.filter(
            q_content & q_class & q_method & q_resolve
        )
        return object_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        classiffication = Classiffication.objects.all()
        method = Method.objects.all()
        context['classiffication'] = classiffication
        context['method'] = method

        return context


class QuestionCreateView(LoginRequiredMixin, generic.CreateView):
    model = Question
    template_name = 'answer/create.html'
    form_class = QuestionForm

    def form_valid(self, form):
        question = form.save(commit=False)
        question.user = self.request.user
        question.save()
        return redirect('answer:index')


@login_required
def QuestionDetailView(request, pk):
    template_name = 'answer/detail.html'
    object = get_object_or_404(Question, pk=pk)
    form = ReplyForm
    if request.method == 'GET':
        return render(request, template_name, {'object': object, 'form': form})

    if request.method == 'POST':
        post_form = ReplyForm(request.POST)
        if post_form.is_valid():
            reply = post_form.save(commit=False)
            reply.question = object
            reply.user = request.user
            reply.save()
        return render(request, template_name, {'object': object, 'form': form})


class QuestionEditView(LoginRequiredMixin, generic.UpdateView):
    model = Question
    template_name = 'answer/edit.html'
    form_class = QuestionForm

    def get_success_url(self):
        return reverse('answer:detail', kwargs={'pk': self.object.pk})


@require_POST
def delete_question(request, pk):
    question = get_object_or_404(Question, pk=pk)
    if request.user == question.user:
        question.delete()
        return redirect('answer:index')
    return redirect('answer:detail', pk=pk)


@require_POST
def delete_reply(request, question_id, pk):
    reply = get_object_or_404(Reply, pk=pk)
    if request.user == reply.user:
        reply.delete()
    return redirect('answer:detail', pk=question_id)


def ReplyEditView(request, question_id, pk):
    template_name = 'answer/reply_edit.html'
    question = get_object_or_404(Question, pk=question_id)
    reply = get_object_or_404(Reply, pk=pk)
    form = ReplyForm(instance=reply)
    if request.method == 'GET':
        return render(request, template_name, {'object': question, 'reply_id': pk, 'form': form})

    if request.method == 'POST':
        post_form = ReplyForm(request.POST, instance=reply)
        if post_form.is_valid():
            post_form.save()
    return redirect('answer:detail', pk=question_id)

templates/answer/create.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="section">
    <form method="post">

        {% csrf_token %}
        {{ form.media }}

        <div class="field">
            <label class="label">{{ form.classiffication.label }}</label>
            <div class="control">
                <div class="select">
                    {{ form.classiffication }}
                </div>
            </div>
        </div>
        <div class="field">
            <label class="label">{{ form.method.label }}</label>
            <div class="control">
                <div class="select">
                    {{ form.method }}
                </div>
            </div>
        </div>
        <label class="label">{{ form.content.label }}</label>
        {{ form.content }}
        <div class="section">
            <button class="button is-primary is-rounded is-midium  is-fullwidth" type="submit">質問を追加</button>
        </div>
    </form>
</div>

{% endblock %}

templates/answer/detail.html
{% extends 'base.html' %}
{% load markdown_extras %}

{% block title %} Answer {% endblock %}

{% block content %}

<div class="columns main-question">
  <div class="column is-two-thirds">
    <div class="card card-question">

      {% include 'answer/components/question_card_header.html' %}

      <div class="card-content">
        <div class="content">

          {% include 'answer/components/question_content.html' %}

          {% if object.user == user %}
          <div class="field is-grouped is-grouped-centered">
            <p class="control">
              <a class="button is-success is-rounded is-small" href="{% url 'answer:edit' object.pk %}">編集する</a>
            </p>
            <p class="control">
            <form method="post" action="{% url 'answer:delete' object.pk %}">
              {% csrf_token %}
              <button class="button is-danger is-rounded is-small" type="submit"
                onclick='return confirm("削除してもよろしいですか?");'>
                削除する
              </button>
            </form>
            </p>
          </div>
          {% endif %}
        </div>
        <hr />
        {% for reply in object.replies.all %}
        <div>

          {% include 'answer/components/reply_content.html' %}

          <br>
          {% if reply.user == user %}

          <div class="field is-grouped is-grouped-centered">
            <p class="control">
              <a class="button is-success is-rounded is-small"
                href="{% url 'answer:edit-reply' object.pk reply.pk %}">編集する</a>
            </p>
            <p class="control">
            <form method="post" action="{% url 'answer:delete-reply' object.pk reply.pk %}">
              {% csrf_token %}
              <button class="button is-danger is-rounded is-small" type="submit"
                onclick='return confirm("削除してもよろしいですか?");'>
                削除する
              </button>
            </form>
            </p>
          </div>
          {% endif %}

          <hr />
        </div>

        {% endfor %}

        {% if object.resolve is False %}
        <form method="post">
          {% csrf_token %}
          {{ form.media }}
          <label class="label">{{ form.content.label }}</label>
          {{ form.content }}
          <div class="section has-text-centered">
            <button class="button is-info is-rounded is-midium" type="submit">
              回答を追加する
            </button>
          </div>
        </form>
        {% endif %}
      </div>
    </div>
  </div>

  {% include 'answer/components/category_column.html' %}

</div>

{% endblock %}

templates/answer/edit.html
{% extends 'base.html' %}
{% load markdown_extras %}

{% block title %} Answer {% endblock %}

{% block content %}

<div class="columns main-question">
  <div class="column is-two-thirds">

    <div class="card card-question">

      <div class="card-content">
        <div class="content">
          <form method="post">
            {% csrf_token %} {{ form.media }}
            <label class="label">{{ form.classiffication.label }}</label>
            <div class="control">
              <div class="select">
                {{ form.classiffication }}
              </div>
            </div><br>

            <label class="label">{{ form.method.label }}</label>
            <div class="control">
              <div class="select">
                {{ form.method }}
              </div>
            </div><br>
            <label class="label">{{ form.content.label }}</label>
            {{ form.content }}
            <div class="section has-text-centered">
              <button class="button is-info is-rounded is-midium" type="submit">
                質問を更新する
              </button>
            </div>
          </form>
        </div>
        <hr />

        {% for reply in object.replies.all %}

        {% include 'answer/components/reply_content.html' %}
        <hr>

        {% endfor %}

      </div>
    </div>
  </div>

  {% include 'answer/components/category_column.html' %}

</div>

{% endblock %}

templates/answer/index.html
{% extends 'base.html' %}
{% load markdown_extras %}

{% block title %} Top | Answer {% endblock %}

{% block content %}



<div class="columns main-question">
    <div class="column is-two-thirds">

        {% for object in object_list %}

        <div class="card card-question">

            {% include 'answer/components/question_card_header.html' %}

            <div class="card-content">
                <div class="columns">
                    <div class="column is-1">
                        <nav class="level">
                            <div class="level-item has-text-centered">
                                <div>
                                    <p class="heading">
                                        {% if object.resolve is False %}
                                        <span class="tag is-info">受付中</span>
                                        {% else %}
                                        <span class="tag is-danger">解決済</span>
                                        {% endif %}
                                    </p>
                                    <p class="heading">回答</p>
                                    <p class="title">{{ object.replies.count }}</p>
                                </div>
                            </div>
                        </nav>
                    </div>
                    <div class="column">
                        <a class="content has-text-black" href="{% url 'answer:detail' object.pk %}">

                            {% include 'answer/components/question_content.html' %}

                        </a>

                    </div>
                </div>
            </div>
        </div>
        {% endfor %}

        {% include 'pagenate.html' %}
    </div>

    {% include 'answer/components/category_column.html' %}

</div>

{% endblock %}

templates/answer/reply_edit.html
{% extends 'base.html' %}
{% load markdown_extras %}

{% block title %} Answer {% endblock %}

{% block content %}

<div class="columns main-question">
    <div class="column is-two-thirds">
        <div class="card card-question">

            {% include 'answer/components/question_card_header.html' %}

            <div class="card-content">
                <div class="content">

                    {% include 'answer/components/question_content.html' %}

                </div>
                <hr />
                {% for reply in object.replies.all %}
                <div>

                    {% if reply.id == reply_id %}

                    <form method="post">
                        {% csrf_token %}
                        {{ form.media }}
                        <label class="label">{{ form.content.label }}</label>
                        {{ form.content }}
                        <div class="section has-text-centered">
                            <button class="button is-info is-rounded is-midium" type="submit">
                                回答を更新する
                            </button>
                        </div>
                    </form>

                    {% else %}

                    {% include 'answer/components/reply_content.html' %}
                    <br>

                    {% endif %}

                    <hr />
                </div>

                {% endfor %}

            </div>
        </div>
    </div>

    {% include 'answer/components/category_column.html' %}

</div>

{% endblock %}