answer/urls.py
from django.conf.urls import include
from django.urls import path
from .views import IndexView, QuestionCreateView, QuestionDetailView, QuestionEditView, delete_question, delete_reply, ReplyEditView

app_name = 'answer'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('create/', QuestionCreateView.as_view(), name='create'),
    path('<int:pk>/', QuestionDetailView, name='detail'),
    path('<int:pk>/edit/', QuestionEditView.as_view(), name='edit'),
    path('<int:pk>/delete/', delete_question, name='delete'),
    path('<int:question_id>/reply/<int:pk>/delete',
         delete_reply, name='delete-reply'),
    path('<int:question_id>/reply/<int:pk>/edit/',
         ReplyEditView, name='edit-reply'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
from django.urls import path
from django.contrib import admin
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('answer/', include('answer.urls'), name='answer'),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('auth/', include('social_django.urls', namespace='social')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    {% block header %}{% include 'header.html' %}{% endblock %}

    <div class="container">
        {% block content %}{% endblock %}    
    </div>

    {% block footer %}{% include 'footer.html' %}{% endblock %}
    
</body>
</html>

templates/footer.html
<footer class="footer" style="background-color: white;">
    <div class="content has-text-centered">
      <p>
        <strong>Answer</strong> by tomioka-k
      </p>
    </div>
  </footer>

templates/header.html
{% load static %}
<div class="header">
  <div class="container">
    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="{% url 'answer:index' %}">
          <img src="{% static 'image/Answer.png' %}"
            alt="Bulma: Free, open source, and modern CSS framework based on Flexbox" width="112" height="28" />
        </a>
        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>
      <div class="navbar-end">
        <div class="navbar-item">
          <div class="field is-grouped">
            <p class="control">
              <a class="button is-danger is-rounded" href="{% url 'answer:create' %}">
                <span>質問を追加する</span>
              </a>
            </p>
          </div>
        </div>
      </div>
    </nav>
  </div>
</div>

templates/pagenate.html
{% load simple_tags %}

{% if is_paginated %}

<nav class="pagination is-centered" role="navigation" aria-label="pagination" style="margin: 2rem 0 2rem;">
    {% if page_obj.has_previous %}
    <a class="pagination-previous" href="?{%  url_replace request 'page' page_obj.previous_page_number %}"
        style="background-color: white;">前へ
    </a>
    {% endif %}
    {% if page_obj.has_next%}
    <a class="pagination-next" href="?{% url_replace request 'page' page_obj.next_page_number %}"
        style="background-color: white;">次へ</a>
    {% endif %}

    <ul class="pagination-list">

        {% if page_obj.has_previous %}
        {% if page_obj.previous_page_number != 1 %}
        <li><a class="pagination-link" href="?page=1">1</a></li>
        <li><span class="pagination-ellipsis">&hellip;</span></li>
        {% endif %}
        <li><a class="pagination-link" href="?page={{ page_obj.previous_page_number }}">
                {{ page_obj.previous_page_number }}
            </a></li>
        {% endif %}

        <li><a class="pagination-link is-current" href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>
        {% if page_obj.has_next %}
        <li><a class="pagination-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
        </li>
        {% if page_obj.next_page_number != page_obj.paginator.num_pages %}
        <li><span class="pagination-ellipsis">&hellip;</span></li>
        <li><a class="pagination-link" href="?page={{ page_obj.paginator.num_pages }}">
                {{ page_obj.paginator.num_pages}}</a></li>
        {% endif %}
        {% endif %}
    </ul>
</nav>

{% endif %}